trigger:
  - release/*

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  CelCash:galaxId: ${{ variables.CelCash_galaxId }}
  CelCash:galaxHash: ${{ variables.CelCash_galaxHash }}
  CelCash:baseUrl: ${{ variables.CelCash_baseUrl }}
  JWT:TokenValidityInMinutes: ${{ variables.JWT_TokenValidityInMinutes }}
  JWT:SecretKey: ${{ variables.JWT_SecretKey }}
  JWT:Issuer: ${{ variables.JWT_Issuer }}
  JWT:Audience: ${{ variables.JWT_Audience }}
  ConnectionStrings:AICBankDbConnString: ${{ variables.ConnectionStrings_AICBankDbConnString }}
  Email:Smtp: ${{ variables.Email_Smtp }}
  Email:Port: ${{ variables.Email_Port }}
  Email:User: ${{ variables.Email_User }}
  Email:Password: ${{ variables.Email_Password }}
  API_PATH: "src/AICBank.API/"

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.303'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      dotnet restore
    displayName: 'Restaurar pacotes Nuget'

  - script: |
      dotnet build $(API_PATH) --configuration $(buildConfiguration)
    displayName: 'Build'

  - script: |
      dotnet publish $(API_PATH) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
    displayName: 'Publish'
    
  - task: FileTransform@1
    displayName: 'Transformar appsettings.json'
    inputs:
      folderPath: '$(Build.ArtifactStagingDirectory)' # Caminho do diretório base
      targetFiles: '**/appsettings.json' # Arquivo que será transformado
    
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: 'drop'
      #publishLocation: 'Container'

  - task: DownloadSecureFile@1  # Baixar a chave privada no pipeline
    inputs:
      secureFile: 'id_rsa'  # Nome do arquivo secure

  - script: |
      mkdir -p ~/.ssh
      cp $(Agent.TempDirectory)/id_rsa ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa

      # Usar SCP para copiar os arquivos para o servidor VPS
      scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r $(Build.ArtifactStagingDirectory)/* root@207.244.247.46:/sistemas/aicbank/api
    displayName: 'Copiar arquivos para o VPS'

  # - script: |
  #     mkdir -p ~/.ssh
  #     cp $(Agent.TempDirectory)/id_rsa ~/.ssh/id_rsa
  #     chmod 600 ~/.ssh/id_rsa
      
  #     ssh -i ~/.ssh/id_rsa root@207.244.247.46
  #     sudo systemctl restart sistema-agendamentos
  #   displayName: 'Reiniciar o Serviço'
